title: "Cong Tech Blog"
description: "A tech blog about CUDA programming"
baseurl: "/congtechblog"
url: "https://luongthecong123.github.io"

markdown: kramdown
theme: minima

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
